spring:
  application:
    name: SpringBootConsumerForNewKey

  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /
    username: root
    password: password
#    listener:
#      simple:
#        acknowledge-mode: manual

server:
  port: 8082